### ISSUE TITLE
Coordinate change

### ISSUE THREAD

**Issue by binxxx** [crigroup/optitrack#1]
Hi, 

Firstly  I'd like to thank you for your contributions for this ROS package. Recently, I am using your package and another package called crazyflie_ros to do research on that. Right now I'm just get started with this. Since there is not much people working with crazyflie using your ROS package, so I'd like to just ask you for further information. The problem is, I heard about that, optitrack uses left coordinate while ROS uses right coordinate, to flip the axis. I had followed some instructions online to revise the rigid_bodies_publisher.py, while the outcome is not satisfying. It seems to make the simulation even worse. Here is the document I read about.([](https://www.dropbox.com/s/073w546dxrx2k0u/Optitrack%20to%20ROS%20frames.pdf?dl=0)) I myself is not familiar with Python, so I really have trouble to understanding all the code in the rigid_bodies_publisher, so I really hope you can help explain or give me some advice. 

```{python}
if rigid_body.tracking_valid and (rospy.get_time()-prevtime[body_id] >= tf_period):
  body_name = 'rigid_body_%d' % (body_id)
  if body_id in ids:
    idx = ids.index(body_id)
    body_name = names[idx]
  # pos2 = np.array([-pos_opt[1],pos_opt[0],pos_opt[2]])
  # rot2 = np.array([-rot_opt[1],rot_opt[0],rot_opt[2],rot_opt[3]])
  # pos2 = np.array([pose.position.x, pose.position.y, pose.position.z])
  # rot2 = np.array([pose.orientation.x, pose.orientation.y, pose.orientation.z, pose.orientation.w])
  # pos2 = np.array([-pose.position.y, pose.position.x, pose.position.z])
  # rot2 = np.array([-pose.orientation.y, pose.orientation.x, pose.orientation.z, pose.orientation.w])
  # tf_broadcaster.sendTransform(pos2, rot2, rospy.Time.now(), body_name, optitrack_frame)
  tf_broadcaster.sendTransform(pos_opt, rot_opt, rospy.Time.now(), body_name, optitrack_frame)
  prevtime[body_id] = rospy.get_time()
``` 

The code I am trying to revise is as above. Any help would be appreciate. Thanks.

**Comment by binxxx** [comment]
![image](https://cloud.githubusercontent.com/assets/19181168/23105179/b6328d98-f6a8-11e6-98e0-face4d6406d7.png)
The code above is not clear, so I post this picture.

**Comment by fsuarez6** [comment]
@byronxubin what do you mean with *left* and *right* coordinates?

**Comment by binxxx** [comment]
@fsuarez6 From what I have found, the output of the optitrack is left handed coordinate, while the ROS uses right handed coordinate. Sorry for not making it clear.

**Comment by fsuarez6** [comment]
Can you share what you have found? (e.g. link)

**Comment by byronxubin** [comment]
[https://www.dropbox.com/s/073w546dxrx2k0u/Optitrack%20to%20ROS%20frames.pdf?dl=0](url)

**Comment by binxxx** [comment]
[Optitrack to ROS frames.pdf](https://github.com/crigroup/optitrack/files/786527/Optitrack.to.ROS.frames.pdf)

**Comment by fsuarez6** [comment]
I see. You just need to apply a rotation to the pose reported by optitrack.
From your pdf, it would be something like this:
```{python}
Toffset = np.array( [0, 1, 0, 0],
                    [0, 0, 1, 0],
                    [1, 0, 0, 0],
                    [0, 0, 0, 1] )
Tros = np.dot(Toptitrack, Toffset)
```
I'm closing this issue because it's related to the way your reference system is defined.
You may want to read more about [homogeneous transformations](https://pdfs.semanticscholar.org/4b6e/a546637a86030b43a7d5ed5873a67d451b4f.pdf).
